x-shared-configuration: &shared-configuration
  image: iiycbka/habit_server:latest
  restart: unless-stopped
  environment:
    DEBUG: "False"
    SECRET_KEY: ${SECRET_KEY}
    DJANGO_ADMIN_URL: ${DJANGO_ADMIN_URL}

    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_HOST: ${POSTGRES_HOST}
    POSTGRES_PORT: ${POSTGRES_PORT}

    DJANGO_HOST: ${DJANGO_HOST}
    DJANGO_ADMIN_IP: ${DJANGO_ADMIN_IP}
    CLIENT_URL: ${CLIENT_URL}

    CELERY_BROKER_URL: ${CELERY_BROKER_URL}
    CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    CACHE_BROKER_URL: ${CACHE_BROKER_URL}

    EMAIL_API_KEY: ${EMAIL_API_KEY}

    REFRESH_GRACE_SECRET: ${REFRESH_GRACE_SECRET}
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_healthy

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    <<: *shared-configuration
    command: "gunicorn"
    networks:
      - backend
      - frontend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - static_data:/app/static

  client:
    image: iiycbka/habit_client:latest
    restart: unless-stopped
    networks:
      - frontend
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - static_data:/app/static:ro
    networks:
      - backend
      - frontend
    depends_on:
      server:
        condition: service_healthy
      client:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"${REDIS_PASSWORD}\" ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery-worker:
    <<: *shared-configuration
    command: "celery_worker"
    networks:
      - backend

  celery-beat:
    <<: *shared-configuration
    command: "celery_beat"
    networks:
      - backend
    volumes:
      - beat_data:/data

volumes:
  postgres_data:
  redis_data:
  static_data:
  beat_data:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
