# Generated by Django 5.2 on 2025-08-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_code_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code_created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
