# Generated by Django 5.2 on 2025-09-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_socialaccount_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('yandex', 'Yandex'), ('x', 'X')], max_length=20),
        ),
    ]
