# Generated by Django 5.2 on 2025-10-11 06:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_device_userdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
